# Generated by Django 3.0.7 on 2021-07-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчики',
                'ordering': ('user__username',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='ExportAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Доступ к экспорту',
                'verbose_name_plural': 'Доступ к экспорту',
                'ordering': ('user__username',),
                'get_latest_by': 'id',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(db_index=True, help_text='Сумма заказа', verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата создания заказа', verbose_name='Дата')),
                ('customer', models.ForeignKey(help_text='Заказчик', on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='api_order.Customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('customer__user__username',),
                'get_latest_by': 'id',
            },
        ),
    ]
