# Generated by Django 3.0.7 on 2021-07-23 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='exportaccess',
            name='user',
            field=models.ForeignKey(help_text='Пользователь с доступом к экспорту заказов', on_delete=django.db.models.deletion.CASCADE, related_name='allowed_to_export', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(help_text='Заказчик', on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL, verbose_name='Заказчик'),
        ),
    ]
